### ISSUE TITLE
support 23.3.0

### ISSUE THREAD

**Issue by hetbo** [TangoAgency/material-intro-screen#59]
Hi
I added this library to my project 
and I tried to build gradle
but it needed support libraries 25.0.1
while I use 23.3.0
I wanna keep using this
so is there any way that I can use this library and keep using support library version 23.3.0
????

**Comment by radzio** [comment]
Why you don't upgrade to 25.0.1? We will not downgrade material intro screen dependencies.

**Comment by hetbo** [comment]
Well I know that
But I have my reasons for myself 
I'm looking for a way to do it
Is there any way?
for example if I can change it by myself for my project and use it.
also I have the same problem with some other libraries .
So if you have something that could help I'll be so happy if help me.

**Comment by radzio** [comment]
You can try to clone this repo and just modify library:
 * downgrade *compileSdkVersion*
 * downgrade *buildTools*
 * downgrade *support libraries*
 * downgrade *targetSDK*

Or you can try to exclude dependency like [here](http://stackoverflow.com/a/39332108/408613) (just exclude support libraries).

IMO it will much easier for you to upgrade your project. More and more libs will start to have the support library 25.x version so it will be really hard for you to downgrade all of them. 

I don't know what are your reasons but for me any other solution than upgrading your project are just strange :>.

I'm closing this issue because. 

Cheers!
